name: authentication
description: "A new Flutter plugin project."
version: 0.0.1
publish_to: 'none'

environment:
  sdk: ^3.5.3
  flutter: '>=3.3.0'

dependencies:
  bloc: ^8.1.4
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  lint: ^2.3.0

flutter:
  uses-material-design: true
